package net.lzbook.kit.data.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import net.lzbook.kit.appender_loghub.ServerLog;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SERVER_LOG".
*/
public class ServerLogDao extends AbstractDao<ServerLog, Long> {

    public static final String TABLENAME = "SERVER_LOG";

    /**
     * Properties of entity ServerLog.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property EventType = new Property(1, String.class, "eventType", false, "EVENT_TYPE");
        public final static Property TimeStamp = new Property(2, String.class, "timeStamp", false, "TIME_STAMP");
        public final static Property ContentJson = new Property(3, String.class, "contentJson", false, "CONTENT_JSON");
    }


    public ServerLogDao(DaoConfig config) {
        super(config);
    }
    
    public ServerLogDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SERVER_LOG\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"EVENT_TYPE\" TEXT," + // 1: eventType
                "\"TIME_STAMP\" TEXT," + // 2: timeStamp
                "\"CONTENT_JSON\" TEXT);"); // 3: contentJson
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SERVER_LOG\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ServerLog entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String eventType = entity.getEventType();
        if (eventType != null) {
            stmt.bindString(2, eventType);
        }
 
        String timeStamp = entity.getTimeStamp();
        if (timeStamp != null) {
            stmt.bindString(3, timeStamp);
        }
 
        String contentJson = entity.getContentJson();
        if (contentJson != null) {
            stmt.bindString(4, contentJson);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ServerLog entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String eventType = entity.getEventType();
        if (eventType != null) {
            stmt.bindString(2, eventType);
        }
 
        String timeStamp = entity.getTimeStamp();
        if (timeStamp != null) {
            stmt.bindString(3, timeStamp);
        }
 
        String contentJson = entity.getContentJson();
        if (contentJson != null) {
            stmt.bindString(4, contentJson);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ServerLog readEntity(Cursor cursor, int offset) {
        ServerLog entity = new ServerLog( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // eventType
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // timeStamp
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // contentJson
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ServerLog entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEventType(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTimeStamp(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setContentJson(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ServerLog entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ServerLog entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ServerLog entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
